[package]
name = "hyper-ownership"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.9.0"
hyper = { version = "0.14.11", features = ["full"] }
hyper-tls = "0.5.0"
log = "0.4.14"
tokio = { version = "1.9.0", features = ["full"] }
